sdap_url: "https://ideas-digitaltwin.jpl.nasa.gov/nexus"
variables:
  - "CO"
units: ''
dataset: "TROPOMI_CO_global"
identifier: "TROPOMI_CO_NE_USA"
description: "TROPOMI Carbon Monoxide Northeast USA"
instrument: "TROPOMI"
bbox: {'min_lon': -81, 'max_lon': -65, 'min_lat': 34, 'max_lat': 50}
start_time: "2023-06-07"
end_time: "2023-06-08"
label_time: "2023-06-07"
interpolation: 5